sudo: required
language: ruby
cache: bundler
dist: trusty

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_install:
  - export TZ=America/New_York
before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - cp config/database.yml.example config/database.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - mysql -e 'create database test_sparc_request;'
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake assets:precompile
jobs:
  include:
    - script:
      - bundle exec rspec --fail-fast spec/features/catalog spec/features/catalog_manager spec/features/confirmation spec/features/review spec/features/service_details
    - script:
      - bundle exec rspec --fail-fast spec/features/dashboard spec/features/document_management spec/features/happy_spec.rb spec/features/obtain_research_pricing spec/features/protocol spec/features/service_calendar spec/features/service_subsidy spec/features/surveyor
    # - script:
    #   - bundle exec rspec spec/api
    #   - bundle exec rspec spec/extensions
    #   - bundle exec rspec spec/jobs
    #   - bundle exec rspec spec/helpers
    #   - bundle exec rspec spec/mailers
    #   - bundle exec rspec spec/lib
    #   - bundle exec rspec spec/models
    #   - bundle exec rspec spec/views
    #   - bundle exec rspec spec/controllers
